name: Python Workflow
on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo yum install -y python3-pip
        python3 -m pip install --upgrade pip
        pip3 install flask  # Install Flask module
        #pip install pytest  # Install pytest
        

    - name: Deploy application
      run: |
       pwd
       sudo yum install docker -y
       sudo service docker start
       sudo docker build -t vinod .
       sudo docker run -itd --name c33 -p 5000:5000 vinod 

