name: Python Workflow
on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    #- name: Set up Python
      #uses: actions/setup-python@v2
      #with:
        #python-version: 3.9 # Replace 'x' with the desired Python version

    - name: Install dependencies
      run: |
        sudo yum install -y python3-pip

        python3 -m pip install --upgrade pip
        pip3 install flask  # Install Flask module
        #pip install pytest  # Install pytest
        

    - name: Deploy application
      run: |
       
       pwd
       sudo yum install docker -y
       sudo service docker start
       sudo docker build -t gta .
       sudo docker run -itd --name c1 -p 5000:5000 gta 

