name: Python Workflow
on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    #- name: Set up Python
      #uses: actions/setup-python@v2
      #with:
        #python-version: 3.9 # Replace 'x' with the desired Python version

    - name: Install dependencies
      run: |
        sudo yum install -y python3
        python3 -m pip install --upgrade pip
        pip install flask  # Install Flask module
        #pip install pytest  # Install pytest
        

    - name: Deploy application
      run: |
       pwd
       who
       sudo -s
       yum install docker -y
       service docker start
       docker build -t gta .
       docker run -itd --name c1 -p 5000:5000 gta 

       #sudo nohup python a.py > /dev/null 2>&1 &
